[package]
name = "rustycheckers"
version = "0.1.0"
authors = ["Daniel Velasquez <dvn228@nyu.edu>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
mut_static = "5.0.0"
lazy_static = "1.0.2"
wasm-bindgen = "0.2.63"
web-sys = { version = "0.3.40", features = [ 'console' ] }
